services:
  node-app:
    container_name: node-app-container
    image: eihabahmed/tresmerge-docker
    ports:
      - 4000:4000
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
      # - postgres
  # postgres:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - postgres-db:/var/lib/postgresql
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: example
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH_ENABLED: false
  #     # ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
  #     # ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
  #   depends_on:
  #     - mongo
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

volumes:
  mongo-db:
  # postgres-db:
